# `render.yaml` - Configuração para o Render Blueprint

# Este arquivo define os serviços que o Render irá criar e gerenciar
# para sua aplicação.

services:
  # Serviço para a aplicação de backend (Spring Boot)
  - type: web
    name: dizzme-backend
    env: docker
    dockerfilePath: Dockerfile # Caminho para o Dockerfile do backend

  # Serviço para a aplicação de frontend (Angular)
  - type: web
    name: dizzme-frontend
    env: docker
    dockerfilePath: Dockerfile # Caminho para o Dockerfile do frontend


  # Serviço para o banco de dados PostgreSQL
  - type: psql
    name: dizzme-postgres
    plan: starter # Plano de banco de dados, "starter" é bom para começar
