services:
  - type: web
    name: dizzme-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    envVars:

      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false