server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dizzme-platform

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET:dizzme-super-secret-key-for-jwt-tokens-2024}
      expiration: 86400000 # 24 hours in milliseconds

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.dizzme: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO

dizzme:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
