services:
  - type: web
    name: dizzme-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    envVars:
      # 1. Variáveis do Banco de Dados: O Render resolve as referências do Blueprint
      #    e injeta a URL e as credenciais REAIS no ambiente do container.
      - key: DATABASE_URL
        value: ${dizzme-postgres.JDBC_DATABASE_URL}
      - key: DATABASE_USERNAME
        value: ${dizzme-postgres.user}
      - key: DATABASE_PASSWORD
        value: ${dizzme-postgres.password}

      # 2. Variáveis da Aplicação: São lidas do Painel do Render (Dashboard).
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false