server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: dizzme-platform

  # Configuração de Datasource que usa as variáveis padrão injetadas pelo Render
  datasource:
    # Render fornece a URL JDBC completa aqui.
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dizzme}
    # Opcional, mas mais robusto usar as variáveis separadas fornecidas pelo Render
    username: ${DATABASE_USERNAME:dizzme_user}
    password: ${DATABASE_PASSWORD:dizzme_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Criar e dropar as tabelas automaticamente no banco novo.
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    jwt:
      secret: ${JWT_SECRET:dizzme-super-secret-key-for-jwt-tokens-2024}
      expiration: 86400000 # 24 hours in milliseconds

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: false
    locations: classpath:db/migration

logging:
  level:
    com.dizzme: INFO
    org.springframework.security: DEBUG
    org.springframework.web: INFO

dizzme:
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
